#!/bin/bash

rm -rf Result_Problems
mkdir Result_Problems

for filename in Problems/*.json; do
	echo "STARTED $PWD/$filename at $(date)"
	echo "STARTED $PWD/$filename at $(date)" >> Result_Problems/_log.txt
	./play_icfp2015 -f "$PWD/$filename" > "Result_$filename"
	# echo "$PWD/$filename" > "Result_$filename"
	echo "ENDED $PWD/$filename at $(date)"
	echo "ENDED $PWD/$filename at $(date)" >> Result_Problems/_log.txt
done
